### ISSUE TITLE
Update OSF for trimmed reads and everything post alignment

### ISSUE THREAD

**Issue by hputnam** [hputnam/Geoduck_Meth#4]
https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/032120-fds/

https://osf.io/yem8n/

**Comment by sr320** [comment]
transferring files to desktop

**Comment by sr320** [comment]
new sorted bams and indices are now updated

**Comment by sr320** [comment]
5x and 10 bedgraphs updated

**Comment by shellywanamaker** [comment]
@sr320 @kubu4 ever got tried this for uploading files? [https://osfclient.readthedocs.io/en/latest/](https://osfclient.readthedocs.io/en/latest/)

**Comment by sr320** [comment]
I have not - are you using it?

**Comment by kubu4** [comment]
Also have not used it.

**Comment by shellywanamaker** [comment]
I tried but I keep getting this error:

```
osf -p yem8n -u strigg@uw.edu upload /Volumes/web/metacarcinus/Pgenerosa/analyses/20200320/TG_FASTQS/EPI-41_S38_L005_R1_001_val_1.fq.gz osfstorage/trimmed
Please input your password: 
usage: osf upload [-h] [-f] [-r] source destination
osf upload: error: You are not authorized to access this project.
```
I even tried changing the the project write access settings to all OSF users and that still didn't resolve the problem (it's now switched back to contributors). After looking through the issues for that software it doesn't seem very robust and doesn't appear to have good support [https://github.com/osfclient/osfclient/issues](https://github.com/osfclient/osfclient/issues). 

It's going to take me a while to upload the trimmed reads (96GB). I'm currently copying files to my desktop from Gannet (~4 min/file) and have to do it in batches because i don't have enough local space to do it all at once. And uploading one file at a time. 

How do we check the integrity of the files uploaded?

**Comment by shellywanamaker** [comment]
also @kubu4 @sr320 what do you think is the most efficient way to upload files to OSF?

**Comment by shellywanamaker** [comment]
it's ~20min to upload 1 file

**Comment by sr320** [comment]
I can get the trimmed files up no problem…

Also it is probably worth setting up a way to work on campus machines remotely.

**Comment by sr320** [comment]
Use that time to wrap up…..

the oyster intro.

**Comment by sr320** [comment]
Also do feel free to upgrade your local space as Sam did.

**Comment by shellywanamaker** [comment]
@sr320 that would be awesome if you could upload the trimmed data!

it's all the *.fq.gz here: [https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200320/TG_FASTQS/](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200320/TG_FASTQS/)

**Comment by sr320** [comment]
Actually I used /gscratch/scrubbed/strigg/analyses/20200320/TG_FASTQS/

**Comment by shellywanamaker** [comment]
I can remote onto the campus machines via terminal, but since can't transfer files of OSF via command line that doesn't help. When I'm on campus I can use the screen sharing application to connect to ostrich for GUI access but I can't get it to connect from home. 

What are you thinking in terms of "setting up a way to work on campus machines remotely."?

/gscratch/scrubbed/strigg/analyses/20200320/TG_FASTQS/ is fine (it's the same contents as https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200320/TG_FASTQS/

**Comment by sr320** [comment]
I find GUI remote very handy on a daily basis using Remote Desktop
I use it of independent rsync operations, OSF uploads, downloading UW restricted content…

**Comment by sr320** [comment]
Update: bismark coverage files uploaded

**Comment by shellywanamaker** [comment]
what's Remote Desktop?

**Comment by sr320** [comment]
see https://github.com/RobertsLab/resources/issues/876

**Comment by sr320** [comment]
trimmed reads, merged 5x tab, coverage files, bams, and bedgraphs updated.
